rule preprocessing_all:
    input:
        #### PROS
        "data/pros/lncap/wt01/operations/preprocessing/LNCaP-WT-01.rep1.refhg38.preprocessing.complete",
        "data/pros/lncap/wt02/operations/preprocessing/LNCaP-WT-02.rep1.refhg38.preprocessing.complete",
        "data/pros/lncap/cr01/operations/preprocessing/LNCaP-CR-01.rep1.refhg38.preprocessing.complete",
        "data/pros/lncap/cr02/operations/preprocessing/LNCaP-CR-02.rep1.refhg38.preprocessing.complete",
        "data/pros/lncap/cr04/operations/preprocessing/LNCaP-CR-04.rep1.refhg38.preprocessing.complete",
        "data/pros/lncap/cr05/operations/preprocessing/LNCaP-CR-05.rep1.refhg38.preprocessing.complete",
        "data/pros/lncap/cr07/operations/preprocessing/LNCaP-CR-07.rep1.refhg38.preprocessing.complete",
        "data/pros/lncap/cr08/operations/preprocessing/LNCaP-CR-08.rep1.refhg38.preprocessing.complete",
        #### COAD
        "data/coad/h508/wt01/operations/preprocessing/H508-WT-01.rep1.refhg38.preprocessing.complete",
        "data/coad/h508/wt02/operations/preprocessing/H508-WT-02.rep1.refhg38.preprocessing.complete",
        "data/coad/h508/wt03/operations/preprocessing/H508-WT-03.rep1.refhg38.preprocessing.complete",
        "data/coad/h508/wt04/operations/preprocessing/H508-WT-04.rep1.refhg38.preprocessing.complete",
        "data/coad/h508/wt05/operations/preprocessing/H508-WT-05.rep1.refhg38.preprocessing.complete",
        "data/coad/h508/wt06/operations/preprocessing/H508-WT-06.rep1.refhg38.preprocessing.complete",
        #
        "data/coad/hs675t/wt01/operations/preprocessing/Hs675T-WT-01.rep1.refhg38.preprocessing.complete",
        "data/coad/hs675t/wt02/operations/preprocessing/Hs675T-WT-02.rep1.refhg38.preprocessing.complete",
        "data/coad/hs675t/wt03/operations/preprocessing/Hs675T-WT-03.rep1.refhg38.preprocessing.complete",
        #
        "data/coad/ls1034/wt01/operations/preprocessing/LS1034-WT-01.rep1.refhg38.preprocessing.complete",
        "data/coad/ls1034/wt02/operations/preprocessing/LS1034-WT-02.rep1.refhg38.preprocessing.complete",
        "data/coad/ls1034/wt03/operations/preprocessing/LS1034-WT-03.rep1.refhg38.preprocessing.complete",
        "data/coad/ls1034/wt04/operations/preprocessing/LS1034-WT-04.rep1.refhg38.preprocessing.complete",
        "data/coad/ls1034/wt05/operations/preprocessing/LS1034-WT-05.rep1.refhg38.preprocessing.complete",
        "data/coad/ls1034/wt06/operations/preprocessing/LS1034-WT-06.rep1.refhg38.preprocessing.complete",
        #
        "data/coad/mdst8/wt01/operations/preprocessing/MDST8-WT-01.rep1.refhg38.preprocessing.complete",
        "data/coad/mdst8/wt02/operations/preprocessing/MDST8-WT-02.rep1.refhg38.preprocessing.complete",
        #
        "data/coad/snu16/wt01/operations/preprocessing/SNU16-WT-01.rep1a.refhg38.preprocessing.complete",
        "data/coad/snu16/wt02/operations/preprocessing/SNU16-WT-01.rep2a.refhg38.preprocessing.complete",
        "data/coad/snu16/wt03/operations/preprocessing/SNU16-WT-01.rep3a.refhg38.preprocessing.complete",
        "data/coad/snu16/wt04/operations/preprocessing/SNU16-WT-01.rep1f.refhg38.preprocessing.complete",
        "data/coad/snu16/wt05/operations/preprocessing/SNU16-WT-01.rep2f.refhg38.preprocessing.complete",
        "data/coad/snu16/wt06/operations/preprocessing/SNU16-WT-01.rep3f.refhg38.preprocessing.complete",
        #
        "data/coad/snu61/wt01/operations/preprocessing/SNU61-WT-01.rep1.refhg38.preprocessing.complete",
        "data/coad/snu61/wt02/operations/preprocessing/SNU61-WT-01.rep2.refhg38.preprocessing.complete",
        "data/coad/snu61/wt03/operations/preprocessing/SNU61-WT-01.rep3.refhg38.preprocessing.complete",
        #### PANC
        "data/panc/capan1/wt01r1/operations/preprocessing/CAPANI-WT-01-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/capan1/wt01r2/operations/preprocessing/CAPANI-WT-01-RUN2.rep1.refhg38.preprocessing.complete",
        "data/panc/capan1/wt02r1/operations/preprocessing/CAPANI-WT-02-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/capan1/wt02r2/operations/preprocessing/CAPANI-WT-02-RUN2.rep1.refhg38.preprocessing.complete",
        "data/panc/capan1/wt03r1/operations/preprocessing/CAPANI-WT-03-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/capan1/wt03r2/operations/preprocessing/CAPANI-WT-03-RUN2.rep1.refhg38.preprocessing.complete",
        #
        "data/panc/hpafii/wt01r1/operations/preprocessing/HPAFII-WT-01-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/hpafii/wt01r2/operations/preprocessing/HPAFII-WT-01-RUN2.rep1.refhg38.preprocessing.complete",
        "data/panc/hpafii/wt02r1/operations/preprocessing/HPAFII-WT-02-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/hpafii/wt02r2/operations/preprocessing/HPAFII-WT-02-RUN2.rep1.refhg38.preprocessing.complete",
        "data/panc/hpafii/wt03r1/operations/preprocessing/HPAFII-WT-03-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/hpafii/wt03r2/operations/preprocessing/HPAFII-WT-03-RUN2.rep1.refhg38.preprocessing.complete",
        #
        "data/panc/kp4/wt01r1/operations/preprocessing/KP4-WT-01-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/kp4/wt01r2/operations/preprocessing/KP4-WT-01-RUN2.rep1.refhg38.preprocessing.complete",
        "data/panc/kp4/wt02r1/operations/preprocessing/KP4-WT-02-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/kp4/wt02r2/operations/preprocessing/KP4-WT-02-RUN2.rep1.refhg38.preprocessing.complete",
        "data/panc/kp4/wt03r1/operations/preprocessing/KP4-WT-03-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/kp4/wt03r2/operations/preprocessing/KP4-WT-03-RUN2.rep1.refhg38.preprocessing.complete",
        #
        "data/panc/panc1/wt01r1/operations/preprocessing/PANC1-WT-01-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/panc1/wt01r2/operations/preprocessing/PANC1-WT-01-RUN2.rep1.refhg38.preprocessing.complete",
        "data/panc/panc1/wt02r1/operations/preprocessing/PANC1-WT-02-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/panc1/wt02r2/operations/preprocessing/PANC1-WT-02-RUN2.rep1.refhg38.preprocessing.complete",
        "data/panc/panc1/wt03r1/operations/preprocessing/PANC1-WT-03-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/panc1/wt03r2/operations/preprocessing/PANC1-WT-03-RUN2.rep1.refhg38.preprocessing.complete",
        #
        "data/panc/panc0403/wt01r1/operations/preprocessing/PANC0403-WT-01-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/panc0403/wt01r2/operations/preprocessing/PANC0403-WT-01-RUN2.rep1.refhg38.preprocessing.complete",
        "data/panc/panc0403/wt02r1/operations/preprocessing/PANC0403-WT-02-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/panc0403/wt02r2/operations/preprocessing/PANC0403-WT-02-RUN2.rep1.refhg38.preprocessing.complete",
        "data/panc/panc0403/wt03r1/operations/preprocessing/PANC0403-WT-03-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/panc0403/wt03r2/operations/preprocessing/PANC0403-WT-03-RUN2.rep1.refhg38.preprocessing.complete",
        #
        "data/panc/patu8ss89/wt01r1/operations/preprocessing/PATU8SS89-WT-01-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/patu8ss89/wt01r2/operations/preprocessing/PATU8SS89-WT-01-RUN2.rep1.refhg38.preprocessing.complete",
        "data/panc/patu8ss89/wt02r1/operations/preprocessing/PATU8SS89-WT-02-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/patu8ss89/wt02r2/operations/preprocessing/PATU8SS89-WT-02-RUN2.rep1.refhg38.preprocessing.complete",
        "data/panc/patu8ss89/wt03r1/operations/preprocessing/PATU8SS89-WT-03-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/patu8ss89/wt03r2/operations/preprocessing/PATU8SS89-WT-03-RUN2.rep1.refhg38.preprocessing.complete",
        #
        "data/panc/pk45h/wt01r1/operations/preprocessing/PK45H-WT-01-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/pk45h/wt01r2/operations/preprocessing/PK45H-WT-01-RUN2.rep1.refhg38.preprocessing.complete",
        "data/panc/pk45h/wt02r1/operations/preprocessing/PK45H-WT-02-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/pk45h/wt02r2/operations/preprocessing/PK45H-WT-02-RUN2.rep1.refhg38.preprocessing.complete",
        "data/panc/pk45h/wt03r1/operations/preprocessing/PK45H-WT-03-RUN1.rep1.refhg38.preprocessing.complete",
        "data/panc/pk45h/wt03r2/operations/preprocessing/PK45H-WT-03-RUN2.rep1.refhg38.preprocessing.complete",

rule preprocessing_lncap:
    input:
        "data/pros/lncap/wt01/operations/preprocessing/LNCaP-WT-01.rep1.refhg38.preprocessing.complete",
        "data/pros/lncap/wt02/operations/preprocessing/LNCaP-WT-02.rep1.refhg38.preprocessing.complete",
        "data/pros/lncap/cr01/operations/preprocessing/LNCaP-CR-01.rep1.refhg38.preprocessing.complete",
        "data/pros/lncap/cr02/operations/preprocessing/LNCaP-CR-02.rep1.refhg38.preprocessing.complete",
        "data/pros/lncap/cr04/operations/preprocessing/LNCaP-CR-04.rep1.refhg38.preprocessing.complete",
        "data/pros/lncap/cr05/operations/preprocessing/LNCaP-CR-05.rep1.refhg38.preprocessing.complete",
        "data/pros/lncap/cr07/operations/preprocessing/LNCaP-CR-07.rep1.refhg38.preprocessing.complete",
        "data/pros/lncap/cr08/operations/preprocessing/LNCaP-CR-08.rep1.refhg38.preprocessing.complete"