---
title: "motifMerging"
author: "Jordan S. Kesner"
date: "December 7, 2018"
output: html_document
---


Install/load
```{r}
# R packages
# install.packages("RCurl")
# install.packages("ggplot2")
# install.packages("stringr")
# install.packages("devtools")
# install.packages("cluster")
# install.packages("seriation")
#install.packages("igraph")
# install.packages("dplyr")
# install.packages("mclust")
# devtools::install_github("r-lib/crayon")
# Bioconductor packages
# source("https://bioconductor.org/biocLite.R")
# biocLite("ATACseqQC", suppressUpdates = TRUE)
# biocLite("ChIPpeakAnno", suppressUpdates = TRUE)
# biocLite("MotifDb", suppressUpdates=TRUE)
# biocLite("BSgenome.Hsapiens.UCSC.hg38", suppressUpdates = TRUE)
# biocLite("TxDb.Hsapiens.UCSC.hg38.knownGene", suppressUpdates = TRUE)
# biocLite("phastCons100way.UCSC.hg38", suppressUpdates = TRUE)
# biocLite("MotIV", suppressUpdates = TRUE)
# biocLite("seqLogo", suppressUpdates = TRUE)
# biocLite("PWMEnrich", suppressUpdates = TRUE)
# biocLite("GenomicRanges", suppressUpdates = TRUE)
# biocLite("stringi", suppressUpdates = TRUE)
# biocLite("ensembldb", suppressUpdates = TRUE)
#biocLite("EnsDb.Hsapiens.v86", suppressUpdates = TRUE)
# biocLite("S4Vectors", suppressUpdates = TRUE)
# biocLite("Rsubread", suppressUpdates = TRUE)
#biocLite("Repitools", suppressUpdates = TRUE)
# biocLite("affxparser", suppressUpdates = TRUE)
#install.packages("partitions")
#install.packages("gmp")
# Load libraries
library(ATACseqQC)
library(ggplot2)
library(reshape2)
library(seriation)
library(igraph)
library(dplyr)
library(cluster)
library(mclust)
library(BSgenome.Hsapiens.UCSC.hg38)
library(MotifDb)
library(GenomicRanges)
library(crayon)
library(MotifDb)
library(MotIV)
library(seqLogo)
library(stringr)
library(PWMEnrich)
library(partitions)
library(Repitools)
library(ensembldb)
library(EnsDb.Hsapiens.v86)
library(S4Vectors)
library(ChIPpeakAnno)
library(Rsamtools)
#library(Rsubread)

```


Load two signal objects
```{r}

load("F:/atac/h508_wt_01/sites/CDX2_motif1_wg_sites.RData")
load("F:/atac/h508_wt_01/sigs/CDX2_motif2_wg_signals.RData")

```



```{r}

sites1 <- H508_WT_01_CDX2_motif1_wg_signals$bindingSites
sites2 <- H508_WT_01_CDX2_motif2_wg_signals$bindingSites
sites3 <- H508_WT_01_CDX2_motif3_wg_signals$bindingSites
sites4 <- H508_WT_01_CDX2_motif4_wg_signals$bindingSites

len <- length(sites2)
sites2@ranges@width <- as.integer(rep(8, len))
len <- length(sites3)
sites3@ranges@width <- as.integer(rep(8, len))
len <- length(sites4)
sites4@ranges@width <- as.integer(rep(8, len))

## this takes way too long
#for (a in 1:len){
  #sites2[a]@ranges@width <- as.integer(8)}

#fun <- function(x){x <- sites2@ranges@width-2
#return(x)}

#sites2@ranges@width <- lapply(sites2@ranges@width, fun)


# union can be used to merge
sites_merge <- union(sites1, sites2, ignore.strand=FALSE)
sites_merge <- union(sites_merge, sites3, ignore.strand=FALSE)
sites_merge <- union(sites_merge, sites4, ignore.strand=FALSE)

sites_clean <- reduce(sites_merge)





```




