## Install libraries, if necessary
source("https://bioconductor.org/biocLite.R")
biocLite("GenomicRanges", suppressUpdates = TRUE)
biocLite("stats4", suppressUpdates = TRUE)
biocLite("BiocGenerics", suppressUpdates = TRUE)
biocLite("parallel", suppressUpdates = TRUE)
biocLite("Rsamtools", suppressUpdates = TRUE)
biocLite("GenomicAlignments", suppressUpdates = TRUE)
biocLite("genomation", suppressUpdates = TRUE)
biocLite("seqLogo", suppressUpdates = TRUE)
biocLite("ChIPpeakAnno", suppressUpdates = TRUE)
install.packages("ggplot2")
install.packages("ggpubr")
biocLite("BSgenome.Hsapiens.UCSC.hg38", suppressUpdates = TRUE)
biocLite("Biostrings", suppressUpdates = TRUE)
biocLite("MotifDb", suppressUpdates = TRUE)
biocLite("VariantAnnotation", suppressUpdates = TRUE)