#if (!requireNamespace("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
BiocManager::install("aracne.networks", version = "3.8")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("annotate")
BiocManager::install("viper")
BiocManager::install("AnnotationDbi")
BiocManager::install("ATACseqQC")
BiocManager::install("MotifDb")
BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
BiocManager::install("Rsamtools")
BiocManager::install("ChIPpeakAnno")
BiocManager::install("GenomicAlignments")
BiocManager::install("BiocGenerics")
BiocManager::install("parallel")
install.packages("rlist")


## Install libraries, if necessary
#source("https://bioconductor.org/biocLite.R")
#biocLite("GenomicRanges", suppressUpdates = TRUE)
#biocLite("stats4", suppressUpdates = TRUE)
#biocLite("BiocGenerics", suppressUpdates = TRUE)
#biocLite("parallel", suppressUpdates = TRUE)
#biocLite("Rsamtools", suppressUpdates = TRUE)
#biocLite("GenomicAlignments", suppressUpdates = TRUE)
#biocLite("genomation", suppressUpdates = TRUE)


## Install libraries, if necessary
#source("https://bioconductor.org/biocLite.R")
#biocLite("GenomicRanges", suppressUpdates = TRUE)
#biocLite("stats4", suppressUpdates = TRUE)
#biocLite("BiocGenerics", suppressUpdates = TRUE)
#biocLite("parallel", suppressUpdates = TRUE)
#biocLite("Rsamtools", suppressUpdates = TRUE)
#biocLite("GenomicAlignments", suppressUpdates = TRUE)
#biocLite("genomation", suppressUpdates = TRUE)
#biocLite("seqLogo", suppressUpdates = TRUE)
#biocLite("ChIPpeakAnno", suppressUpdates = TRUE)
#install.packages("ggplot2")
#install.packages("ggpubr")
