##
## Install libraries, if necessary
source("https://bioconductor.org/biocLite.R")
##
biocLite("BiocGenerics", suppressUpdates = TRUE)
biocLite("GenomicRanges", suppressUpdates = TRUE)
biocLite("GenomicAlignments", suppressUpdates = TRUE)
biocLite("VariantAnnotation", suppressUpdates = TRUE)
biocLite("BiSeq", suppressUpdates = TRUE)
biocLite("Rsamtools", suppressUpdates = TRUE)
biocLite("genomation", suppressUpdates = TRUE)
biocLite("stats4", suppressUpdates = TRUE)
biocLite("seqLogo", suppressUpdates = TRUE)
biocLite("MotifDb", suppressUpdates = TRUE)
biocLite("BSgenome.Hsapiens.UCSC.hg38", suppressUpdates = TRUE)
biocLite("ChIPpeakAnno", suppressUpdates = TRUE)
biocLite("AnnotationDbi", suppressUpdates = TRUE)
biocLite("viper", suppressUpdates = TRUE)
biocLite("annotate", suppressUpdates = TRUE)
biocLite("org.Hs.eg.db", suppressUpdates = TRUE)
biocLite("aracne.networks", suppressUpdates = TRUE)
##
install.packages("rlist")
install.packages("ggpubr")
install.packages("ggplot2")